spring:
  application:
    name: apigw

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"

resilience4j.circuitbreaker:
  instances:
    customerCircuitBreaker:
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowSize: 10

server:
  port: 8083



