services:
  db:
    container_name: postgres1
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 23099
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin1
    image: elestio/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "nbavsunovsky@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: 23099
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "5050:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - postgres
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=nibavs
      - RABBITMQ_DEFAULT_PASS=23099
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: unless-stopped


networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:





